name: PRGuard Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: PRGuard Rules Review
        uses: 1137043480/PRGuard@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
